# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pg-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"


# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pg-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: GeminiFarm
            - name: POSTGRES_PASSWORD
              value: Gemini
            - name: POSTGRES_DB
              value: GeminiFarm_db
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
              subPath: pg-data
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
